class Ipl
{
public static void main(String arg[])
{
String rcbPlayers[]={"vk","faf","maxwell","siraj","krishna","arjun rawat","josh","hasaranga","patel","dk","ahmed"};
System.out.println("playing rcbPlayers 11 are:");
System.out.println(rcbPlayers [0]);
System.out.println(rcbPlayers [1]);
System.out.println(rcbPlayers [2]);
System.out.println(rcbPlayers [3]);
System.out.println(rcbPlayers [4]);
System.out.println(rcbPlayers [5]);
System.out.println(rcbPlayers [6]);
System.out.println(rcbPlayers [7]);
System.out.println(rcbPlayers [8]);
System.out.println(rcbPlayers [9]);
System.out.println(rcbPlayers [10]);
String cskPlayers[]={"msd","devon","rutu","subhranshu","ajinkya","shaik","jadeja","dwaine","mitchell","ali" ,"ambati"};
System.out.println("Playing cskPlayers 11 are:");
System.out.println(cskPlayers [0]);
System.out.println(cskPlayers [1]);
System.out.println(cskPlayers [2]);
System.out.println(cskPlayers [3]);
System.out.println(cskPlayers [4]);
System.out.println(cskPlayers [5]);
System.out.println(cskPlayers [6]);
System.out.println(cskPlayers [7]);
System.out.println(cskPlayers [8]);
System.out.println(cskPlayers [9]);
System.out.println(cskPlayers [10]);
String gtPlayers[]={"pandya","gill","kane","rashid","david","joseph","darshan","jayant","pradeep","wade" ,"abhinav"};
System.out.println("Playing gtPlayers 11 are:");
System.out.println(gtPlayers [0]);
System.out.println(gtPlayers [1]);
System.out.println(gtPlayers [2]);
System.out.println(gtPlayers [3]);
System.out.println(gtPlayers [4]);
System.out.println(gtPlayers [5]);
System.out.println(gtPlayers [6]);
System.out.println(gtPlayers [7]);
System.out.println(gtPlayers [8]);
System.out.println(gtPlayers [9]);
System.out.println(gtPlayers [10]);
String dcPlayers[]={"abhishek","prithvi","david","sarfarz","yash","rovman","anrich","kamlesh","rahaman","lunnii" ,"ambati"};
System.out.println("Playing dcPlayers 11 are:");
System.out.println(dcPlayers [0]);
System.out.println(dcPlayers [1]);
System.out.println(dcPlayers [2]);
System.out.println(dcPlayers [3]);
System.out.println(dcPlayers [4]);
System.out.println(dcPlayers [5]);
System.out.println(dcPlayers [6]);
System.out.println(dcPlayers [7]);
System.out.println(dcPlayers [8]);
System.out.println(dcPlayers [9]);
System.out.println(dcPlayers [10]);
String kkrPlayers[]={"nitish","rinku","varun","tim","umesh","andre","venkatesh","sunil","ankul","lockie","harshit"};
System.out.println("Playing kkrPlayers 11 are:");
System.out.println(kkrPlayers [0]);
System.out.println(kkrPlayers [1]);
System.out.println(kkrPlayers [2]);
System.out.println(kkrPlayers [3]);
System.out.println(kkrPlayers [4]);
System.out.println(kkrPlayers [5]);
System.out.println(kkrPlayers [6]);
System.out.println(kkrPlayers [7]);
System.out.println(kkrPlayers [8]);
System.out.println(kkrPlayers [9]);
System.out.println(kkrPlayers [10]);
String lsgPlayers[]={"manan","kl rahul","quinton de","ravi bishnoi","mohsin khan","mayank","avesh","mark wood","karan","k gowtham","deepak"};
System.out.println("Playing lsgPlayers 11 are:");
System.out.println(lsgPlayers [0]);
System.out.println(lsgPlayers [1]);
System.out.println(lsgPlayers [2]);
System.out.println(lsgPlayers [3]);
System.out.println(lsgPlayers [4]);
System.out.println(lsgPlayers [5]);
System.out.println(lsgPlayers [6]);
System.out.println(lsgPlayers [7]);
System.out.println(lsgPlayers [8]);
System.out.println(lsgPlayers [9]);
System.out.println(lsgPlayers [10]);
String pbksPlayers[]={"bhanuka","shahrukh","prabhsimarn","jitesh","arshdeep","raj bawad","harpreet","rabada","balte","liam" ,"rishi"};
System.out.println("Playing pbksPlayers 11 are:");
System.out.println(pbksPlayers [0]);
System.out.println(pbksPlayers [1]);
System.out.println(pbksPlayers [2]);
System.out.println(pbksPlayers [3]);
System.out.println(pbksPlayers [4]);
System.out.println(pbksPlayers [5]);
System.out.println(pbksPlayers [6]);
System.out.println(pbksPlayers [7]);
System.out.println(pbksPlayers [8]);
System.out.println(pbksPlayers [9]);
System.out.println(pbksPlayers [10]);
String miPlayers[]={"rohit sharma","suryakumar","tilak","ramandeep","dewald","ishan","jasprit","kartikeya","jofra","hrithik" ,"arjun"};
System.out.println("Playing miPlayers 11 are:");
System.out.println(miPlayers [0]);
System.out.println(miPlayers [1]);
System.out.println(miPlayers [2]);
System.out.println(miPlayers [3]);
System.out.println(miPlayers [4]);
System.out.println(miPlayers [5]);
System.out.println(miPlayers [6]);
System.out.println(miPlayers [7]);
System.out.println(miPlayers [8]);
System.out.println(miPlayers [9]);
System.out.println(miPlayers [10]);
String rrPlayers[]={"yashasvi jaiswal","padikkal","shimron","sanju samson","buttler","dhruv","kuldip","navdeep","obed","kc nijalingappa" ,"riyan parag"};
System.out.println("Playing rrPlayers 11 are:");
System.out.println(rrPlayers [0]);
System.out.println(rrPlayers [1]);
System.out.println(rrPlayers [2]);
System.out.println(rrPlayers [3]);
System.out.println(rrPlayers [4]);
System.out.println(rrPlayers [5]);
System.out.println(rrPlayers [6]);
System.out.println(rrPlayers [7]);
System.out.println(rrPlayers [8]);
System.out.println(rrPlayers [9]);
System.out.println(rrPlayers [10]);
String srhPlayers[]={"aiden","rahul","glenn","umarn malik","karthik","fazal","t natarajan","bhuvneshwar","abdul samad","marco jansen" ,"washington"};
System.out.println("Playing srhPlayers 11 are:");
System.out.println(srhPlayers [0]);
System.out.println(srhPlayers [1]);
System.out.println(srhPlayers [2]);
System.out.println(srhPlayers [3]);
System.out.println(srhPlayers [4]);
System.out.println(srhPlayers [5]);
System.out.println(srhPlayers [6]);
System.out.println(srhPlayers [7]);
System.out.println(srhPlayers [8]);
System.out.println(srhPlayers [9]);
System.out.println(srhPlayers [10]);
}
}